export const FETCH_FRIENDS_LIST = "FETCH_FRIENDS_LIST";
export const FETCH_PENDING_REQUESTS = "FETCH_PENDING_REQUESTS";
export const RECEIVE_FRIENDS_LIST = "RECEIVE_FRIENDS_LIST";
export const RECEIVE_PENDING_REQUESTS = "RECEIVE_PENDING_REQUESTS";

export const GET_FRIENDSHIP_STATUS = "GET_FRIENDSHIP_STATUS";

export const ADD_FRIEND = "ADD_FRIEND";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const REJECT_FRIEND_REQUEST = "REJECT_FRIEND_REQUEST";
export const BLOCK_FRIEND = "BLOCK_FRIEND";

export const REMOVE_FRIEND = "REMOVE_FRIEND";
